### PR TITLE
Fix ordering and boolean search

### PR DESCRIPTION
**Pull request by doganmeh**
So I am resubmitting my patchy fixes for the issues at hand, just to shed light on the problem
UPDATE: I just fetched upstream/master since issues are resolved. So, intended PR commits are gone!

### CODE REVIEW

**Comment by tiliv** [comment]
I've addressed the sorting issue by going a little closer to the core reason for the error in 08ba02e.  Sometime after Django 1.7, their ``MultipleObjectMixin`` started including ``ordering = None`` as a class attribute, and we were blindly forwarding that ``None`` into the meta constructor.

**Comment by tiliv** [comment]
I still haven't recreated the boolean problem using the latest code, though.  I'm not sure what would be the next step in debugging that.

**Comment by doganmeh** [comment]
> haven't recreated the boolean problem using the latest code

do you mean it does not happen in your repo? does http://127.0.0.1:8080/choices-fields/ search 'True' fine for you?

**Comment by doganmeh** [comment]
Here I created a test.

**Comment by doganmeh** [comment]
And this test for ordering.

**Comment by tiliv** [comment]
Thanks for the tests. The code in the example works for me, but it looks like my home internet connection died. Once I'm back online I'll pull this down and see how the test runs.

**Comment by tiliv** [comment]
If you revert the two commits that are code changes (and just keep the tests), does ``DatatableTests.test_search_term_boolean`` fail for you?  I'm on your branch (with those two code commits reverted) and it's passing for me.

**Comment by doganmeh** [comment]
They passed on my working branch since I had my own patches. I had also
checked-out and tried upstream/master as well and they passed as well. I
did not revert patches to try tests. Are you trying to see if tests fail
when they need to?

**Comment by tiliv** [comment]
Well, it sounded like you see an error with searches on master, but I haven't been able to reproduce that today.  It leads me to think we can bring in the tests you made, but I don't think we need the code changes.

Specifically from above:

> > haven't recreated the boolean problem using the latest code
> do you mean it does not happen in your repo? does http://127.0.0.1:8080/choices-fields/ search 'True' fine for you?

That is correct.  On master on my repo, the search for ``"True"`` works fine as far as I can tell.

**Comment by doganmeh** [comment]
I just tried tests against your latest commit on 10/4 (Allow deliberate None values) and both failed. Seems what you have done yesterday fixed it. Will you pull test for future reference?

**Pull request merged**
