### PR TITLE
Fixes compatibility issues with django 1.10

### PR DESCRIPTION
**Pull request by jangeador**
This branch merges the changes proposed by Anna Prochowska on 59b46ca plus it fixes compatibility issues related to django 1.10 and the new model._meta API.

### CODE REVIEW

**Comment by jangeador** [comment]
I missed one of the functions in utils.py. I am sending an ammended pull request.

**Comment by sheagcraig** [comment]
Until this gets merged, I've been happily using this with a Django 1.10 project.

**Comment by jangeador** [comment]
That's good to hear. Your Python-jss library has saved me lots of time. Very nice work @sheagcraig

**Comment by doganmeh** [comment]
Is this branch stale? Tiliv has not been around for a long time..

**Comment by tiliv** [comment]
I've unfortunately been very busy these last several months and regret not having cleaned everything up yet.  I was 99.99% ready to release when I got derailed on a live examine documentation server.

Realistically, I will need about 1 month more of hiatus, but this branch should still work fine.  After that I'm eager to get this thing sparkling again for the latest Django and datatables.js versions.

A heartfelt thanks has to go to the compatibility forks that have carried people forward while my attention has been elsewhere.

**Comment by jangeador** [comment]
@tiliv great to hear from you. We will be waiting until you get back. In the meantime, if there is anything I can help with let me know.

**Comment by doganmeh** [comment]
I was saddened to think the best wrapper to best js grid app for the best python web framework was losing leadership.. I am glad I was wrong. I just came across this project yesterday, though, let me know too if I can help.

**Comment by sheagcraig** [comment]
Awesome. How does this work with the pypi package. I imagine you have to do a release and/or actually push to pypi, and that this PR doesn't in itself constitute a release.

Also, @jangeador I'm frankly shocked that you have even heard of, no less used python-jss. Small world I guess!

**Comment by tiliv** [comment]
I want to comb through a few things before I do a proper release, and also get the latest live demos set up outside of App Engine, which is doomed to be inadequate.  I'll try to stay on this for a release in the next couple of weeks (I'm leaving town for a while after that).

**Comment by doganmeh** [comment]
Do you also plan to remove the legacy configuration and its code? We really need to get the basics (e.g., paging, sorting, filtering, etc.) solid, so I think a clean-up would help. Also, as you review things, if you add more explanation here and there, especially function docstrings, that would help tremendously when debugging. When I read the code I see what it is doing, but not necessarily what it is meant to be doing :) which is crucial for debugging.

**Comment by tiliv** [comment]
0.9 and 1.0 will be identical and released at the same time, except that 1.0 will have the legacy syntax removed (so that people needing a softer transition can use 0.9 until they are ready to make the switch).

**Comment by doganmeh** [comment]
Perfect. I might be on the 0.9 side :)

I am still not fully aware of the benefits of the new syntax. For example,
I wonder the use cases/advantages of defining a column as such:

head_line = columns.TextColumn(..

since type information is already in the Django model..

**Comment by tiliv** [comment]
``Datatable.Meta.columns`` will let you name columns you want to appear without declaring the whole thing from scratch.  The whole of ``Datatable.Meta`` is basically the old ``View.datatable_options`` dict, except you can give names in ``columns`` that refer to virtual fields declared on the class.

In most cases, you won't need to redeclare the column from scratch unless you intend to build a compound column or use a non-default Column type.

**Comment by doganmeh** [comment]
1. And my benefit of using compound column over just a processor is that, it can filter underlying fields?

But under the new scheme, we won't be able to do this anymore:

`columns =  ['id', ("Publication Date", 'pub_date', 'pub_processor'), 'headline']`

right?

**Comment by tiliv** [comment]
That's correct.  The fuzzy line between old and new syntax comes from the fact that the old column spec works in 0.9 inside of ``Datatable.Meta.columns``, which is a fluke of having the legacy code actually transforming its view dict into a Datatable with Meta on the fly so that everything can go through the same pipeline.

**Comment by doganmeh** [comment]
I just tried the old column spec in `Datatable.Meta.columns` and it did not work :) so does that mean we are not there yet for 0.9?

**Comment by tiliv** [comment]
Looks like I spoke without brushing up on the final decision I made before.  To keep things clear cut, you should use ``LegacyDatatable`` as the parent class for your Datatable class (from the same import path as the regular one).  It has a virtual column handler that sets out to translate the legacy syntax.

I'll have to go over it once we get some of these bumps fixed with the recent changes to make sure it's all working as advertised before release.  Hopefully I won't misspeak too many times about how it works while I settle back in :P

**Comment by doganmeh** [comment]
I don't know what is the audience like, but would consider speeding up the transition if I were you. Fixing a 2-in-1 system is harder more than 2X.. You have to look at it from both ways, and It will be complicated. Unless you are damn careful and put in a lot of time and effort, it will not work well from either side, worse yet, possibly from both sides..

**Pull request closed without merging**
