### PR TITLE
Fixed unreferenced local variable in Datatable pagination

### PR DESCRIPTION
**Pull request by devictr**
Hi,

I got an UnboundLocalVariableError while using this pull request https://github.com/pivotal-energy-solutions/django-datatable-view/issues/148, because paginations weren't working.
Even if you don't plan on merging the aforementioned pull request, I think this is a import fix that could avoid things breaking in the future.

Thanks for your work !
Cheers,
Victor

### CODE REVIEW

**Comment by michaeldjeffrey** [comment]
Your change appears to completely bypass the pagination, even when things are working correctly.
Do you know what was going on that that was causing that check to not be passed?

**Comment by devictr** [comment]
Thanks for your reply. Yes I just figured, my bad for pushing too quickly. I'll check tomorrow and get back to you then.

**Comment by devictr** [comment]
I just pushed a fix. Sorry, the `object_list` variable was not used anymore if a pagination length was defined.
I don't know exactly why I got an `UnboundLocalError` when checking out the pull request https://github.com/pivotal-energy-solutions/django-datatable-view/issues/148.

**Comment by tiliv** [comment]
Thanks!  That's quite an odd mistake in the method!

**Pull request merged**
