### PR TITLE
Please review this work

### PR DESCRIPTION
**Pull request by davidfischer-ch**
It contains some simple fixes like PEP8 warnings but also implements a generic way to handle new fields types through handlers user can register.

I would like to know your thoughts about it.

Thanks.

### CODE REVIEW

**Comment by PamelaM** [comment]
Note: I am *not* the maintainer of this project, and I know that I'm 3 months late to the party, but my comments are as follows:

I like the refactoring into type handlers and think it's a good approach.  

 - Please break this into three PRs:  
   - PEP-8 specific changes 
   - Field type refactoring
   - queryset.distinct() change (if the distinct() is an integral part of the field type refactor, then please comment on that in the code

 - Please add a set of unit tests for the feature, including covering all new type handlers (some of which are probably already covered via existing tests) and adding a field_type and field_handler
 - This isn't a show-stopper for the PR, but I don't see a mechanism for registering a type handler programatically.  This could get tricky because, properly, there should be *two* FIELD_TYPE/FIELD_HANDLER lists - one global (as exists now) and one that's unique the a given ListView - so there might be the following both module functions (  ```datatableview.utils.register_field_handler/type()```)  and and DatatableView methods (```DatatableView. register_field_handler/type()```)

**Comment by davidfischer-ch** [comment]
Hello,

Thanks for reviewing my pull request.

Unfortunately I am busy until next week doing my mandatory military time (Switzerland).

If someone can cherry-pick etc for me it will be awesome. Otherwise I will have time next week.

Again, thanks.

**Comment by tiliv** [comment]
I will be going through this set of changes today and applying them in a way that I'm comfortable with.  Some of these issues have been resolved in my 1.0 branch, so I'll naturally elect to not take some of these changes just so that we don't end up with an api change just to have it change again in 1.0.

The good news is that the 1.0 branch rocks, so there's that.

Thanks to both of you for your efforts concerning these changes.

**Comment by tiliv** [comment]
I've made the following changes by hand from the original PR:

Encoding declarations: https://github.com/pivotal-energy-solutions/django-datatable-view/commit/b6e52a6e9e0c9815d0075b8712883ab31d1a5719
PEP-8 spacing: https://github.com/pivotal-energy-solutions/django-datatable-view/commit/2f90ccfcd9776e8a70215683ff915c2669b4b5b1 and https://github.com/pivotal-energy-solutions/django-datatable-view/commit/124b1aed6c2f8a82fda61259dc443d4ebcf1ab82 and https://github.com/pivotal-energy-solutions/django-datatable-view/commit/6fd897356b8d3e0bf7314225620cc0db5aea68d4
Unused imports/locals: https://github.com/pivotal-energy-solutions/django-datatable-view/commit/5fa1eaf6a847014b689f47fb08d51764902d367d and https://github.com/pivotal-energy-solutions/django-datatable-view/commit/130efa19951892c2c91e2699a34dc3547e61e9c7
Fix for ugettext coercion: https://github.com/pivotal-energy-solutions/django-datatable-view/commit/688f08dcd16b26a09d1a7023f3999efa70173500
``FIELD_TYPES`` as a defaultdict: https://github.com/pivotal-energy-solutions/django-datatable-view/commit/e5f059718013d008e2d73a4ff6c41043e960b902
``queryset.distinct()``: https://github.com/pivotal-energy-solutions/django-datatable-view/commit/73697e1245bdca665edebcbd56531bc24c09f743

I'm leaving out the individual field type handlers in favor of the 1.0 strategy I'll be releasing in the near future.  The way it was approached in the PR makes sense, and I even did this myself at one point, but organizationally it makes me queazy.  1.0 will use classes to declare columns, akin to the way forms have Field classes, and all of this work will be encapsulated there.

**Comment by davidfischer-ch** [comment]
Hello,

Next time please use git cherry-pick to pick-up individual commits.
I just remarked you *swallowed* my work.

**Comment by tiliv** [comment]
Sorry.  Thank you for being concerned.  Perhaps the decision wasn't the correct one.

I was influenced by the long-fixed ugettext, queryset.distinct(), and correct imports changes on the rework branch.  FIELD_TYPES is obsoleted, but that one surely deserved a cherry-pick.  The field handler callback system also would have certainly been handled differently had I been merging that work.

But I understand, and I was conscious of the situation when I made additional attribute in the commit messages.

**Pull request closed without merging**
